services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=16&charset=utf8
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
      JWT_SECRET_KEY: '%kernel.project_dir%/config/jwt/private.pem'
      JWT_PUBLIC_KEY: '%kernel.project_dir%/config/jwt/public.pem'
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
    depends_on:
      - database
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
volumes:
  db_data: