<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260421125444 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE obtention (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_obtention TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, iteration_avant_obtention INT DEFAULT NULL, notes TEXT DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, version_id INT NOT NULL, methode_obtention_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7A35A2B3FB88E14F ON obtention (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_7A35A2B34BBC2705 ON obtention (version_id)');
        $this->addSql('CREATE INDEX IDX_7A35A2B3DDD0B17C ON obtention (methode_obtention_id)');
        $this->addSql('CREATE TABLE obtention_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, obtention_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_89389C976BDB9F4B ON obtention_tag (obtention_id)');
        $this->addSql('CREATE INDEX IDX_89389C97BAD26311 ON obtention_tag (tag_id)');
        $this->addSql('CREATE TABLE pokemon_favori (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, pokemon_id INT NOT NULL, version_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_836CDE98FB88E14F ON pokemon_favori (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_836CDE982FE71C3E ON pokemon_favori (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_836CDE984BBC2705 ON pokemon_favori (version_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_utilisateur_pokemon_favori ON pokemon_favori (utilisateur_id, pokemon_id)');
        $this->addSql('ALTER TABLE obtention ADD CONSTRAINT FK_7A35A2B3FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE obtention ADD CONSTRAINT FK_7A35A2B34BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE obtention ADD CONSTRAINT FK_7A35A2B3DDD0B17C FOREIGN KEY (methode_obtention_id) REFERENCES tag (id)');
        $this->addSql('ALTER TABLE obtention_tag ADD CONSTRAINT FK_89389C976BDB9F4B FOREIGN KEY (obtention_id) REFERENCES obtention (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE obtention_tag ADD CONSTRAINT FK_89389C97BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pokemon_favori ADD CONSTRAINT FK_836CDE98FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pokemon_favori ADD CONSTRAINT FK_836CDE982FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (numero) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pokemon_favori ADD CONSTRAINT FK_836CDE984BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur_version DROP CONSTRAINT fk_c5172451fb88e14f');
        $this->addSql('ALTER TABLE utilisateur_version DROP CONSTRAINT fk_c51724514bbc2705');
        $this->addSql('ALTER TABLE utilisateur_version DROP CONSTRAINT fk_c5172451ddd0b17c');
        $this->addSql('DROP TABLE utilisateur_version');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE utilisateur_version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_obtention TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, iteration_avant_obtention INT DEFAULT NULL, notes TEXT DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, version_id INT NOT NULL, methode_obtention_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_c51724514bbc2705 ON utilisateur_version (version_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_utilisateur_version ON utilisateur_version (utilisateur_id, version_id)');
        $this->addSql('CREATE INDEX idx_c5172451ddd0b17c ON utilisateur_version (methode_obtention_id)');
        $this->addSql('CREATE INDEX idx_c5172451fb88e14f ON utilisateur_version (utilisateur_id)');
        $this->addSql('ALTER TABLE utilisateur_version ADD CONSTRAINT fk_c5172451fb88e14f FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE utilisateur_version ADD CONSTRAINT fk_c51724514bbc2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE utilisateur_version ADD CONSTRAINT fk_c5172451ddd0b17c FOREIGN KEY (methode_obtention_id) REFERENCES tag (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE obtention DROP CONSTRAINT FK_7A35A2B3FB88E14F');
        $this->addSql('ALTER TABLE obtention DROP CONSTRAINT FK_7A35A2B34BBC2705');
        $this->addSql('ALTER TABLE obtention DROP CONSTRAINT FK_7A35A2B3DDD0B17C');
        $this->addSql('ALTER TABLE obtention_tag DROP CONSTRAINT FK_89389C976BDB9F4B');
        $this->addSql('ALTER TABLE obtention_tag DROP CONSTRAINT FK_89389C97BAD26311');
        $this->addSql('ALTER TABLE pokemon_favori DROP CONSTRAINT FK_836CDE98FB88E14F');
        $this->addSql('ALTER TABLE pokemon_favori DROP CONSTRAINT FK_836CDE982FE71C3E');
        $this->addSql('ALTER TABLE pokemon_favori DROP CONSTRAINT FK_836CDE984BBC2705');
        $this->addSql('DROP TABLE obtention');
        $this->addSql('DROP TABLE obtention_tag');
        $this->addSql('DROP TABLE pokemon_favori');
    }
}
