<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420081653 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pokemon (numero INT NOT NULL, nom VARCHAR(255) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (numero))');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, categorie VARCHAR(255) DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tag_version (date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id_version INT NOT NULL, id_tag INT NOT NULL, PRIMARY KEY (id_version, id_tag))');
        $this->addSql('CREATE INDEX IDX_8D2DFE6961817AB3 ON tag_version (id_version)');
        $this->addSql('CREATE INDEX IDX_8D2DFE699D2D5FD9 ON tag_version (id_tag)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON utilisateur (username)');
        $this->addSql('CREATE TABLE utilisateur_version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_obtention TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, iteration_avant_obtention INT DEFAULT NULL, notes TEXT DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, version_id INT NOT NULL, methode_obtention_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C5172451FB88E14F ON utilisateur_version (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_C51724514BBC2705 ON utilisateur_version (version_id)');
        $this->addSql('CREATE INDEX IDX_C5172451DDD0B17C ON utilisateur_version (methode_obtention_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_utilisateur_version ON utilisateur_version (utilisateur_id, version_id)');
        $this->addSql('CREATE TABLE version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, nom_fichier_image VARCHAR(255) DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, numero_pokemon INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF1CD3C3A4888E52 ON version (numero_pokemon)');
        $this->addSql('ALTER TABLE tag_version ADD CONSTRAINT FK_8D2DFE6961817AB3 FOREIGN KEY (id_version) REFERENCES version (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tag_version ADD CONSTRAINT FK_8D2DFE699D2D5FD9 FOREIGN KEY (id_tag) REFERENCES tag (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur_version ADD CONSTRAINT FK_C5172451FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur_version ADD CONSTRAINT FK_C51724514BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur_version ADD CONSTRAINT FK_C5172451DDD0B17C FOREIGN KEY (methode_obtention_id) REFERENCES tag (id)');
        $this->addSql('ALTER TABLE version ADD CONSTRAINT FK_BF1CD3C3A4888E52 FOREIGN KEY (numero_pokemon) REFERENCES pokemon (numero) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tag_version DROP CONSTRAINT FK_8D2DFE6961817AB3');
        $this->addSql('ALTER TABLE tag_version DROP CONSTRAINT FK_8D2DFE699D2D5FD9');
        $this->addSql('ALTER TABLE utilisateur_version DROP CONSTRAINT FK_C5172451FB88E14F');
        $this->addSql('ALTER TABLE utilisateur_version DROP CONSTRAINT FK_C51724514BBC2705');
        $this->addSql('ALTER TABLE utilisateur_version DROP CONSTRAINT FK_C5172451DDD0B17C');
        $this->addSql('ALTER TABLE version DROP CONSTRAINT FK_BF1CD3C3A4888E52');
        $this->addSql('DROP TABLE pokemon');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE tag_version');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE utilisateur_version');
        $this->addSql('DROP TABLE version');
    }
}
