<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420093318 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tag_version DROP CONSTRAINT tag_version_pkey');
        $this->addSql('ALTER TABLE tag_version ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE tag_version ADD PRIMARY KEY (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tag_version DROP CONSTRAINT tag_version_pkey');
        $this->addSql('ALTER TABLE tag_version DROP id');
        $this->addSql('ALTER TABLE tag_version ADD PRIMARY KEY (id_version, id_tag)');
    }
}
